// Botswana reference data — villages (with cadastre area + location type)
// and the official 12 Main Land Boards (per "List of Landboards.xlsx").
//
// Location types follow Botswana settlement classification:
//   City · Town · Urban Village · Village

export const VILLAGES = [
  // Existing cadastre mappings preserved (CAD-001 … CAD-020)
  { name: 'Gaborone',        cadastreAreaId: 'CAD-001', locationType: 'City' },
  { name: 'Francistown',     cadastreAreaId: 'CAD-002', locationType: 'City' },
  { name: 'Molepolole',      cadastreAreaId: 'CAD-003', locationType: 'Urban Village' },
  { name: 'Serowe',          cadastreAreaId: 'CAD-004', locationType: 'Urban Village' },
  { name: 'Maun',            cadastreAreaId: 'CAD-005', locationType: 'Urban Village' },
  { name: 'Kanye',           cadastreAreaId: 'CAD-006', locationType: 'Urban Village' },
  { name: 'Mahalapye',       cadastreAreaId: 'CAD-007', locationType: 'Urban Village' },
  { name: 'Mogoditshane',    cadastreAreaId: 'CAD-008', locationType: 'Urban Village' },
  { name: 'Mochudi',         cadastreAreaId: 'CAD-009', locationType: 'Urban Village' },
  { name: 'Lobatse',         cadastreAreaId: 'CAD-010', locationType: 'Town' },
  { name: 'Palapye',         cadastreAreaId: 'CAD-011', locationType: 'Urban Village' },
  { name: 'Ramotswa',        cadastreAreaId: 'CAD-012', locationType: 'Urban Village' },
  { name: 'Tlokweng',        cadastreAreaId: 'CAD-013', locationType: 'Urban Village' },
  { name: 'Jwaneng',         cadastreAreaId: 'CAD-014', locationType: 'Town' },
  { name: 'Selebi-Phikwe',   cadastreAreaId: 'CAD-015', locationType: 'Town' },
  { name: 'Orapa',           cadastreAreaId: 'CAD-016', locationType: 'Town' },
  { name: 'Letlhakane',      cadastreAreaId: 'CAD-017', locationType: 'Urban Village' },
  { name: 'Kasane',          cadastreAreaId: 'CAD-018', locationType: 'Town' },
  { name: 'Ghanzi',          cadastreAreaId: 'CAD-019', locationType: 'Urban Village' },
  { name: 'Tsabong',         cadastreAreaId: 'CAD-020', locationType: 'Village' },
  // Extended national village list
  { name: 'Thamaga',         cadastreAreaId: 'CAD-021', locationType: 'Urban Village' },
  { name: 'Tonota',          cadastreAreaId: 'CAD-022', locationType: 'Urban Village' },
  { name: 'Bobonong',        cadastreAreaId: 'CAD-023', locationType: 'Village' },
  { name: 'Gabane',          cadastreAreaId: 'CAD-024', locationType: 'Village' },
  { name: 'Tutume',          cadastreAreaId: 'CAD-025', locationType: 'Village' },
  { name: 'Moshupa',         cadastreAreaId: 'CAD-026', locationType: 'Village' },
  { name: 'Shakawe',         cadastreAreaId: 'CAD-027', locationType: 'Village' },
  { name: 'Gumare',          cadastreAreaId: 'CAD-028', locationType: 'Village' },
  { name: 'Mmadinare',       cadastreAreaId: 'CAD-029', locationType: 'Village' },
  { name: 'Tati Siding',     cadastreAreaId: 'CAD-030', locationType: 'Village' },
  { name: 'Kopong',          cadastreAreaId: 'CAD-031', locationType: 'Village' },
  { name: 'Metsimotlhabe',   cadastreAreaId: 'CAD-032', locationType: 'Village' },
  { name: 'Oodi',            cadastreAreaId: 'CAD-033', locationType: 'Village' },
  { name: 'Mmopane',         cadastreAreaId: 'CAD-034', locationType: 'Village' },
  { name: 'Tlokweng East',   cadastreAreaId: 'CAD-035', locationType: 'Village' },
  { name: 'Nata',            cadastreAreaId: 'CAD-036', locationType: 'Village' },
  { name: 'Gweta',           cadastreAreaId: 'CAD-037', locationType: 'Village' },
  { name: 'Rakops',          cadastreAreaId: 'CAD-038', locationType: 'Village' },
  { name: 'Shoshong',        cadastreAreaId: 'CAD-039', locationType: 'Village' },
  { name: 'Sefhare',         cadastreAreaId: 'CAD-040', locationType: 'Village' },
  { name: 'Machaneng',       cadastreAreaId: 'CAD-041', locationType: 'Village' },
  { name: 'Sherwood (Zanzibar)', cadastreAreaId: 'CAD-042', locationType: 'Village' },
  { name: 'Sefophe',         cadastreAreaId: 'CAD-043', locationType: 'Village' },
  { name: 'Mmathethe',       cadastreAreaId: 'CAD-044', locationType: 'Village' },
  { name: 'Goodhope',        cadastreAreaId: 'CAD-045', locationType: 'Village' },
  { name: 'Pitsane',         cadastreAreaId: 'CAD-046', locationType: 'Village' },
  { name: 'Digawana',        cadastreAreaId: 'CAD-047', locationType: 'Village' },
  { name: 'Kang',            cadastreAreaId: 'CAD-048', locationType: 'Village' },
  { name: 'Hukuntsi',        cadastreAreaId: 'CAD-049', locationType: 'Village' },
  { name: 'Lehututu',        cadastreAreaId: 'CAD-050', locationType: 'Village' },
  { name: 'Tshabong North',  cadastreAreaId: 'CAD-051', locationType: 'Village' },
  { name: 'Werda',           cadastreAreaId: 'CAD-052', locationType: 'Village' },
  { name: 'Charleshill',     cadastreAreaId: 'CAD-053', locationType: 'Village' },
  { name: 'Dkar',            cadastreAreaId: 'CAD-054', locationType: 'Village' },
  { name: 'Sehithwa',        cadastreAreaId: 'CAD-055', locationType: 'Village' },
  { name: 'Nokaneng',        cadastreAreaId: 'CAD-056', locationType: 'Village' },
  { name: 'Seronga',         cadastreAreaId: 'CAD-057', locationType: 'Village' },
  { name: 'Kazungula',       cadastreAreaId: 'CAD-058', locationType: 'Village' },
  { name: 'Pandamatenga',    cadastreAreaId: 'CAD-059', locationType: 'Village' },
  { name: 'Lentsweletau',    cadastreAreaId: 'CAD-060', locationType: 'Village' },
  { name: 'Letlhakeng',      cadastreAreaId: 'CAD-061', locationType: 'Village' },
  { name: 'Salajwe',         cadastreAreaId: 'CAD-062', locationType: 'Village' },
  { name: 'Bokaa',           cadastreAreaId: 'CAD-063', locationType: 'Village' },
  { name: 'Morwa',           cadastreAreaId: 'CAD-064', locationType: 'Village' },
  { name: 'Pilane',          cadastreAreaId: 'CAD-065', locationType: 'Village' },
  { name: 'Rasesa',          cadastreAreaId: 'CAD-066', locationType: 'Village' },
  { name: 'Artesia',         cadastreAreaId: 'CAD-067', locationType: 'Village' },
  { name: 'Mmankgodi',       cadastreAreaId: 'CAD-068', locationType: 'Village' },
  { name: 'Kumakwane',       cadastreAreaId: 'CAD-069', locationType: 'Village' },
  { name: 'Otse',            cadastreAreaId: 'CAD-070', locationType: 'Village' },
  { name: 'Taung',           cadastreAreaId: 'CAD-071', locationType: 'Village' },
  { name: 'Mogobane',        cadastreAreaId: 'CAD-072', locationType: 'Village' },
  { name: 'Ranaka',          cadastreAreaId: 'CAD-073', locationType: 'Village' },
  { name: 'Lotlhakane',      cadastreAreaId: 'CAD-074', locationType: 'Village' },
  { name: 'Sese',            cadastreAreaId: 'CAD-075', locationType: 'Village' },
  { name: 'Maitengwe',       cadastreAreaId: 'CAD-076', locationType: 'Village' },
  { name: 'Masunga',         cadastreAreaId: 'CAD-077', locationType: 'Village' },
  { name: 'Sebina',          cadastreAreaId: 'CAD-078', locationType: 'Village' },
  { name: 'Nkange',          cadastreAreaId: 'CAD-079', locationType: 'Village' },
  { name: 'Shashe Mooke',    cadastreAreaId: 'CAD-080', locationType: 'Village' },
  { name: 'Borolong',        cadastreAreaId: 'CAD-081', locationType: 'Village' },
  { name: 'Chadibe',         cadastreAreaId: 'CAD-082', locationType: 'Village' },
  { name: 'Mathangwane',     cadastreAreaId: 'CAD-083', locationType: 'Village' },
  { name: 'Ramokgonami',     cadastreAreaId: 'CAD-084', locationType: 'Village' },
  { name: 'Maunatlala',      cadastreAreaId: 'CAD-085', locationType: 'Village' },
  { name: 'Lerala',          cadastreAreaId: 'CAD-086', locationType: 'Village' },
  { name: 'Molalatau',       cadastreAreaId: 'CAD-087', locationType: 'Village' },
  { name: 'Tsetsebjwe',      cadastreAreaId: 'CAD-088', locationType: 'Village' },
  { name: 'Mathathane',      cadastreAreaId: 'CAD-089', locationType: 'Village' },
  { name: 'Sowa Town',       cadastreAreaId: 'CAD-090', locationType: 'Town' },
]

// Quick lookup: village name → { cadastreAreaId, locationType }
export const VILLAGE_LOOKUP = VILLAGES.reduce((acc, v) => {
  acc[v.name] = v
  acc[v.name.toLowerCase()] = v
  return acc
}, {})

// The 12 Main Land Boards in Botswana — from "List of Landboards.xlsx"
export const LAND_BOARDS = [
  'Rolong Land Board',
  'Tati Land Board',
  'Kweneng Land Board',
  'Ngwaketse Land Board',
  'Ghanzi Land Board',
  'Chobe Land Board',
  'Tawana Land Board',
  'Kgalagadi Land Board',
  'Ngwato Land Board',
  'Kgatleng Land Board',
  'Malete Land Board',
  'Tlokweng Land Board',
]
