// Botswana reference data — villages/places (with cadastre area ID + location
// type) from the client's actual "Cadastre_Areas_Converted.xlsx", and the
// official 12 Main Land Boards from "List of LAndboards.xlsx".
//
// Location types are exactly as classified in the source file: Town, Village,
// Farms, National Parks and Forest Reserves — NOT the City/Urban Village
// scheme used in an earlier placeholder version of this file.
//
// Note: a handful of names (e.g. Otse, Chadibe, Toteng) appear twice in the
// source file under different Cadastre Area IDs — an ambiguity in the client's
// own data, not introduced here. Both entries are kept in VILLAGES so either
// is selectable; VILLAGE_LOOKUP (used for auto-fill) resolves to the last one.

export const VILLAGES = [
  { name: "Kasane", cadastreAreaId: "576", locationType: "Town" },
  { name: "Mabele", cadastreAreaId: "579", locationType: "Village" },
  { name: "Kavimba", cadastreAreaId: "580", locationType: "Village" },
  { name: "Kazungula", cadastreAreaId: "575", locationType: "Village" },
  { name: "Ch5", cadastreAreaId: "571", locationType: "Village" },
  { name: "Jwaneng", cadastreAreaId: "179", locationType: "Town" },
  { name: "Diphuduhudu", cadastreAreaId: "41", locationType: "Village" },
  { name: "Shadishadi", cadastreAreaId: "38", locationType: "Village" },
  { name: "Sojwe", cadastreAreaId: "37", locationType: "Village" },
  { name: "Ngware", cadastreAreaId: "40", locationType: "Village" },
  { name: "Lephepe", cadastreAreaId: "36", locationType: "Village" },
  { name: "Loologane", cadastreAreaId: "39", locationType: "Village" },
  { name: "Khekhenye", cadastreAreaId: "48", locationType: "Village" },
  { name: "Motokwe", cadastreAreaId: "47", locationType: "Village" },
  { name: "Takatokwane", cadastreAreaId: "51", locationType: "Village" },
  { name: "Maboane", cadastreAreaId: "52", locationType: "Village" },
  { name: "Tswaane", cadastreAreaId: "49", locationType: "Village" },
  { name: "Dutlwe", cadastreAreaId: "50", locationType: "Village" },
  { name: "Tsetseng", cadastreAreaId: "46", locationType: "Village" },
  { name: "Khutse", cadastreAreaId: "45", locationType: "National Parks and Forest Reserves" },
  { name: "Ramaphatle", cadastreAreaId: "84", locationType: "Village" },
  { name: "Kumakwane", cadastreAreaId: "86", locationType: "Village" },
  { name: "Gakgatla", cadastreAreaId: "82", locationType: "Village" },
  { name: "Thamaga", cadastreAreaId: "83", locationType: "Village" },
  { name: "Mmankgodi", cadastreAreaId: "85", locationType: "Village" },
  { name: "Tloaneng", cadastreAreaId: "92", locationType: "Village" },
  { name: "Mmokolodi", cadastreAreaId: "91", locationType: "Village" },
  { name: "Gabane", cadastreAreaId: "90", locationType: "Village" },
  { name: "Metsimotlhabe", cadastreAreaId: "87", locationType: "Village" },
  { name: "Kaudwane", cadastreAreaId: "44", locationType: "Village" },
  { name: "Salajwe", cadastreAreaId: "43", locationType: "Village" },
  { name: "Malwelwe", cadastreAreaId: "59", locationType: "Village" },
  { name: "Khudumelapye", cadastreAreaId: "53", locationType: "Village" },
  { name: "Sorilatholo", cadastreAreaId: "42", locationType: "Village" },
  { name: "Ditshegwane", cadastreAreaId: "56", locationType: "Village" },
  { name: "Mmatseta", cadastreAreaId: "78", locationType: "Village" },
  { name: "Gakutlo", cadastreAreaId: "79", locationType: "Village" },
  { name: "Ditshukudu", cadastreAreaId: "67", locationType: "Village" },
  { name: "Monwane", cadastreAreaId: "62", locationType: "Village" },
  { name: "Mahetlwe", cadastreAreaId: "68", locationType: "Village" },
  { name: "Gamodubu", cadastreAreaId: "80", locationType: "Village" },
  { name: "Mmonoko", cadastreAreaId: "81", locationType: "Village" },
  { name: "Molepolole", cadastreAreaId: "66", locationType: "Village" },
  { name: "Kubung", cadastreAreaId: "64", locationType: "Village" },
  { name: "Mmantshwabisi", cadastreAreaId: "61", locationType: "Village" },
  { name: "Letlhakeng", cadastreAreaId: "58", locationType: "Village" },
  { name: "Moshaweng", cadastreAreaId: "57", locationType: "Village" },
  { name: "Sesung", cadastreAreaId: "55", locationType: "Village" },
  { name: "Metsibotlhoko", cadastreAreaId: "54", locationType: "Village" },
  { name: "Serinane", cadastreAreaId: "60", locationType: "Village" },
  { name: "Mogoditshane", cadastreAreaId: "89", locationType: "Village" },
  { name: "Losilakgokong", cadastreAreaId: "65", locationType: "Village" },
  { name: "Kotolaname", cadastreAreaId: "63", locationType: "Village" },
  { name: "Mogonono", cadastreAreaId: "69", locationType: "Village" },
  { name: "Hatsalatladi", cadastreAreaId: "70", locationType: "Village" },
  { name: "Botlhapatlou", cadastreAreaId: "71", locationType: "Village" },
  { name: "Mmopane", cadastreAreaId: "88", locationType: "Village" },
  { name: "Lentsweletau", cadastreAreaId: "75", locationType: "Village" },
  { name: "Dikgatlhong", cadastreAreaId: "74", locationType: "Village" },
  { name: "Kopong", cadastreAreaId: "77", locationType: "Village" },
  { name: "Kgope", cadastreAreaId: "76", locationType: "Village" },
  { name: "Medie", cadastreAreaId: "73", locationType: "Village" },
  { name: "Kweneng", cadastreAreaId: "72", locationType: "Village" },
  { name: "Boatlaname", cadastreAreaId: "35", locationType: "Village" },
  { name: "Majwaneng", cadastreAreaId: "446", locationType: "Village" },
  { name: "Lerala", cadastreAreaId: "447", locationType: "Village" },
  { name: "Ratholo", cadastreAreaId: "441", locationType: "Village" },
  { name: "Gootau", cadastreAreaId: "439", locationType: "Village" },
  { name: "Goosekgweng", cadastreAreaId: "438", locationType: "Village" },
  { name: "Mokungwane", cadastreAreaId: "436", locationType: "Village" },
  { name: "Matlhakola", cadastreAreaId: "437", locationType: "Village" },
  { name: "Lecheng", cadastreAreaId: "435", locationType: "Village" },
  { name: "Malaka", cadastreAreaId: "434", locationType: "Village" },
  { name: "Palapye", cadastreAreaId: "433", locationType: "Village" },
  { name: "Topisi", cadastreAreaId: "459", locationType: "Village" },
  { name: "Manaledi", cadastreAreaId: "440", locationType: "Village" },
  { name: "Moeng", cadastreAreaId: "443", locationType: "Village" },
  { name: "Mabeleapodi", cadastreAreaId: "378", locationType: "Village" },
  { name: "Paje", cadastreAreaId: "379", locationType: "Village" },
  { name: "Majwanaadipitse", cadastreAreaId: "377", locationType: "Village" },
  { name: "Malatswai", cadastreAreaId: "380", locationType: "Village" },
  { name: "Tshimoyapula", cadastreAreaId: "461", locationType: "Village" },
  { name: "Gojwane", cadastreAreaId: "462", locationType: "Village" },
  { name: "Dimajwe", cadastreAreaId: "376", locationType: "Village" },
  { name: "Mmashoro", cadastreAreaId: "375", locationType: "Village" },
  { name: "Mabuo", cadastreAreaId: "426", locationType: "Village" },
  { name: "Sehunou", cadastreAreaId: "427", locationType: "Village" },
  { name: "Moiyabana", cadastreAreaId: "425", locationType: "Village" },
  { name: "Motshegaletau", cadastreAreaId: "428", locationType: "Village" },
  { name: "Mogorosi", cadastreAreaId: "431", locationType: "Village" },
  { name: "Serowe", cadastreAreaId: "432", locationType: "Village" },
  { name: "Western Sandveld", cadastreAreaId: "381", locationType: "Village" },
  { name: "Thabala", cadastreAreaId: "429", locationType: "Village" },
  { name: "Dibete", cadastreAreaId: "386", locationType: "Village" },
  { name: "Poloka", cadastreAreaId: "385", locationType: "Village" },
  { name: "Mokgenene", cadastreAreaId: "384", locationType: "Village" },
  { name: "Tobela", cadastreAreaId: "397", locationType: "Village" },
  { name: "Ikongwe", cadastreAreaId: "392", locationType: "Village" },
  { name: "Otse", cadastreAreaId: "382", locationType: "Village" },
  { name: "Mmutlane", cadastreAreaId: "398", locationType: "Village" },
  { name: "Kodibeleng", cadastreAreaId: "383", locationType: "Village" },
  { name: "Shoshong", cadastreAreaId: "396", locationType: "Village" },
  { name: "Moralane", cadastreAreaId: "393", locationType: "Village" },
  { name: "Kalamare", cadastreAreaId: "395", locationType: "Village" },
  { name: "Mosolotshane", cadastreAreaId: "394", locationType: "Village" },
  { name: "Pallaroad", cadastreAreaId: "391", locationType: "Village" },
  { name: "Mahalapye", cadastreAreaId: "400", locationType: "Village" },
  { name: "Tuli Block Farms Palapye", cadastreAreaId: "448", locationType: "Farms" },
  { name: "Tuli Block Farms Sefhare", cadastreAreaId: "404", locationType: "Farms" },
  { name: "Tuli Block Farms Mahalapye", cadastreAreaId: "388", locationType: "Farms" },
  { name: "Makwate", cadastreAreaId: "405", locationType: "Village" },
  { name: "Letoreng", cadastreAreaId: "409", locationType: "Village" },
  { name: "Matlhako", cadastreAreaId: "410", locationType: "Village" },
  { name: "Machaneng", cadastreAreaId: "408", locationType: "Village" },
  { name: "Shakwe", cadastreAreaId: "406", locationType: "Village" },
  { name: "Chadibe", cadastreAreaId: "413", locationType: "Village" },
  { name: "Borotsi", cadastreAreaId: "412", locationType: "Village" },
  { name: "Sefhare", cadastreAreaId: "411", locationType: "Village" },
  { name: "Ngwapa", cadastreAreaId: "415", locationType: "Village" },
  { name: "Mokobeng", cadastreAreaId: "414", locationType: "Village" },
  { name: "Moshopha", cadastreAreaId: "407", locationType: "Village" },
  { name: "Tumasera", cadastreAreaId: "416", locationType: "Village" },
  { name: "Ramokgonami", cadastreAreaId: "417", locationType: "Village" },
  { name: "Maape", cadastreAreaId: "418", locationType: "Village" },
  { name: "Mhalapitsa", cadastreAreaId: "419", locationType: "Village" },
  { name: "Pilikwe", cadastreAreaId: "420", locationType: "Village" },
  { name: "Mookane", cadastreAreaId: "387", locationType: "Village" },
  { name: "Dovedale", cadastreAreaId: "389", locationType: "Village" },
  { name: "Mmaphashalala", cadastreAreaId: "390", locationType: "Village" },
  { name: "Kudumatse", cadastreAreaId: "403", locationType: "Village" },
  { name: "Mokoswane", cadastreAreaId: "402", locationType: "Village" },
  { name: "Taupye", cadastreAreaId: "401", locationType: "Village" },
  { name: "Bonwapitse", cadastreAreaId: "399", locationType: "Village" },
  { name: "Tewane", cadastreAreaId: "422", locationType: "Village" },
  { name: "Mokgware", cadastreAreaId: "424", locationType: "Village" },
  { name: "Mogome", cadastreAreaId: "423", locationType: "Village" },
  { name: "Radisele", cadastreAreaId: "421", locationType: "Village" },
  { name: "Zone 2a", cadastreAreaId: "373", locationType: "Village" },
  { name: "Kaka Ranches", cadastreAreaId: "370", locationType: "Village" },
  { name: "Khwee", cadastreAreaId: "372", locationType: "Village" },
  { name: "Zone 2b", cadastreAreaId: "371", locationType: "Village" },
  { name: "Letlhakane", cadastreAreaId: "374", locationType: "Village" },
  { name: "Kedia", cadastreAreaId: "363", locationType: "Village" },
  { name: "Orapa", cadastreAreaId: "361", locationType: "Village" },
  { name: "Mokubilo", cadastreAreaId: "487", locationType: "Village" },
  { name: "Xere", cadastreAreaId: "368", locationType: "Village" },
  { name: "Mmadikola", cadastreAreaId: "367", locationType: "Village" },
  { name: "Toromoja", cadastreAreaId: "366", locationType: "Village" },
  { name: "Xhumo", cadastreAreaId: "365", locationType: "Village" },
  { name: "Mopipi", cadastreAreaId: "364", locationType: "Village" },
  { name: "Mmeya", cadastreAreaId: "488", locationType: "Village" },
  { name: "Jamataka", cadastreAreaId: "490", locationType: "Village" },
  { name: "Matsitama", cadastreAreaId: "489", locationType: "Village" },
  { name: "Mosu", cadastreAreaId: "359", locationType: "Village" },
  { name: "Marapong", cadastreAreaId: "498", locationType: "Village" },
  { name: "Lepashe", cadastreAreaId: "499", locationType: "Village" },
  { name: "Makgaolakgang", cadastreAreaId: "500", locationType: "Village" },
  { name: "Mmatshumo", cadastreAreaId: "360", locationType: "Village" },
  { name: "Makuta", cadastreAreaId: "505", locationType: "Village" },
  { name: "Rakops", cadastreAreaId: "346", locationType: "Village" },
  { name: "Kutamogoree", cadastreAreaId: "503", locationType: "Village" },
  { name: "Nswazwi", cadastreAreaId: "506", locationType: "Village" },
  { name: "Goshwe", cadastreAreaId: "513", locationType: "Village" },
  { name: "Tutume", cadastreAreaId: "507", locationType: "Village" },
  { name: "Zone6 Ranches", cadastreAreaId: "345", locationType: "Village" },
  { name: "Sowa Town", cadastreAreaId: "358", locationType: "Town" },
  { name: "Moremaoto", cadastreAreaId: "342", locationType: "Village" },
  { name: "Changate", cadastreAreaId: "511", locationType: "Village" },
  { name: "Motopi", cadastreAreaId: "343", locationType: "Village" },
  { name: "Zone 1", cadastreAreaId: "356", locationType: "Village" },
  { name: "Dabgwi", cadastreAreaId: "510", locationType: "Village" },
  { name: "Nkange", cadastreAreaId: "512", locationType: "Village" },
  { name: "Nata", cadastreAreaId: "357", locationType: "Village" },
  { name: "Senete", cadastreAreaId: "508", locationType: "Village" },
  { name: "Zoroga", cadastreAreaId: "348", locationType: "Village" },
  { name: "Manxotae", cadastreAreaId: "355", locationType: "Village" },
  { name: "Maitengwe", cadastreAreaId: "509", locationType: "Village" },
  { name: "Maposa", cadastreAreaId: "354", locationType: "Village" },
  { name: "Gweta", cadastreAreaId: "349", locationType: "Village" },
  { name: "Sepako", cadastreAreaId: "353", locationType: "Village" },
  { name: "Wildlife Management Area", cadastreAreaId: "351", locationType: "Village" },
  { name: "Area 4b Ranches", cadastreAreaId: "369", locationType: "Village" },
  { name: "Mokoboxane", cadastreAreaId: "362", locationType: "Village" },
  { name: "Makgadikgadi National Park", cadastreAreaId: "340", locationType: "National Parks and Forest Reserves" },
  { name: "Wildlife Management Area C...", cadastreAreaId: "347", locationType: "Village" },
  { name: "Tsokatshaa", cadastreAreaId: "350", locationType: "Village" },
  { name: "Mosetse", cadastreAreaId: "502", locationType: "Village" },
  { name: "Dukwi", cadastreAreaId: "501", locationType: "Village" },
  { name: "Nshakashogwe", cadastreAreaId: "504", locationType: "Village" },
  { name: "Mathangwane", cadastreAreaId: "493", locationType: "Village" },
  { name: "Sebina", cadastreAreaId: "496", locationType: "Village" },
  { name: "Makalamabedi", cadastreAreaId: "344", locationType: "Village" },
  { name: "Semitwe", cadastreAreaId: "497", locationType: "Village" },
  { name: "Khumaga", cadastreAreaId: "341", locationType: "Village" },
  { name: "Chadibe", cadastreAreaId: "492", locationType: "Village" },
  { name: "Makobo", cadastreAreaId: "491", locationType: "Village" },
  { name: "Mafungo", cadastreAreaId: "494", locationType: "Village" },
  { name: "Marobela", cadastreAreaId: "495", locationType: "Village" },
  { name: "Wma", cadastreAreaId: "352", locationType: "Village" },
  { name: "Lesenepole", cadastreAreaId: "454", locationType: "Village" },
  { name: "Kgagodi", cadastreAreaId: "455", locationType: "Village" },
  { name: "Mogapi", cadastreAreaId: "451", locationType: "Village" },
  { name: "Mathathane", cadastreAreaId: "471", locationType: "Village" },
  { name: "Tsetsebjwe", cadastreAreaId: "469", locationType: "Village" },
  { name: "Sefhophe", cadastreAreaId: "468", locationType: "Village" },
  { name: "Molalatau", cadastreAreaId: "472", locationType: "Village" },
  { name: "Motlhabaneng", cadastreAreaId: "473", locationType: "Village" },
  { name: "Selebi Phikwe", cadastreAreaId: "466", locationType: "Town" },
  { name: "Semolale", cadastreAreaId: "474", locationType: "Village" },
  { name: "Tobane", cadastreAreaId: "467", locationType: "Village" },
  { name: "Mabolwe", cadastreAreaId: "475", locationType: "Village" },
  { name: "Bobonong", cadastreAreaId: "477", locationType: "Village" },
  { name: "Gobojango", cadastreAreaId: "476", locationType: "Village" },
  { name: "Lepokole", cadastreAreaId: "478", locationType: "Village" },
  { name: "Tshokwe", cadastreAreaId: "479", locationType: "Village" },
  { name: "Robelela", cadastreAreaId: "480", locationType: "Village" },
  { name: "Tonota", cadastreAreaId: "482", locationType: "Village" },
  { name: "Shashemooke", cadastreAreaId: "483", locationType: "Village" },
  { name: "Borolong", cadastreAreaId: "484", locationType: "Village" },
  { name: "Mmadinare", cadastreAreaId: "465", locationType: "Village" },
  { name: "Natale", cadastreAreaId: "485", locationType: "Village" },
  { name: "Mabesekwa", cadastreAreaId: "486", locationType: "Village" },
  { name: "Foley", cadastreAreaId: "481", locationType: "Village" },
  { name: "Damochujenaa", cadastreAreaId: "464", locationType: "Village" },
  { name: "Serule", cadastreAreaId: "463", locationType: "Village" },
  { name: "Moreomabele", cadastreAreaId: "460", locationType: "Village" },
  { name: "Mogapinyana", cadastreAreaId: "456", locationType: "Village" },
  { name: "Diloro", cadastreAreaId: "457", locationType: "Village" },
  { name: "Tamasane", cadastreAreaId: "458", locationType: "Village" },
  { name: "Moremi", cadastreAreaId: "453", locationType: "Village" },
  { name: "Maunatlala", cadastreAreaId: "452", locationType: "Village" },
  { name: "Moletemane", cadastreAreaId: "450", locationType: "Village" },
  { name: "Tuli Block Farms Maunatlala", cadastreAreaId: "449", locationType: "Farms" },
  { name: "Mokokwana", cadastreAreaId: "442", locationType: "Village" },
  { name: "Seolwane", cadastreAreaId: "445", locationType: "Village" },
  { name: "Tuli Block Farms Bobonong", cadastreAreaId: "470", locationType: "Farms" },
  { name: "Mosweu", cadastreAreaId: "444", locationType: "Village" },
  { name: "Sedibeng", cadastreAreaId: "149", locationType: "Village" },
  { name: "Musi", cadastreAreaId: "158", locationType: "Village" },
  { name: "Mokgomane", cadastreAreaId: "148", locationType: "Village" },
  { name: "Tswaaneng", cadastreAreaId: "157", locationType: "Village" },
  { name: "Magoriapitse", cadastreAreaId: "147", locationType: "Village" },
  { name: "Lejwana", cadastreAreaId: "101", locationType: "Village" },
  { name: "Sekhutlane", cadastreAreaId: "156", locationType: "Village" },
  { name: "Kanngwe", cadastreAreaId: "159", locationType: "Village" },
  { name: "Gathwane", cadastreAreaId: "129", locationType: "Village" },
  { name: "Digawana", cadastreAreaId: "100", locationType: "Village" },
  { name: "Gamajaalela", cadastreAreaId: "130", locationType: "Village" },
  { name: "Motsentshe", cadastreAreaId: "146", locationType: "Village" },
  { name: "Gopong", cadastreAreaId: "99", locationType: "Village" },
  { name: "Metlobo", cadastreAreaId: "160", locationType: "Village" },
  { name: "Mogojwagojwe", cadastreAreaId: "132", locationType: "Village" },
  { name: "Mmathethe", cadastreAreaId: "145", locationType: "Village" },
  { name: "Lorolwane", cadastreAreaId: "171", locationType: "Village" },
  { name: "Dipotsana", cadastreAreaId: "133", locationType: "Village" },
  { name: "Molapowabojang", cadastreAreaId: "98", locationType: "Village" },
  { name: "Diabo", cadastreAreaId: "144", locationType: "Village" },
  { name: "Segwagwa", cadastreAreaId: "161", locationType: "Village" },
  { name: "Kgomokasitwa", cadastreAreaId: "97", locationType: "Village" },
  { name: "Lotlhakane East", cadastreAreaId: "135", locationType: "Village" },
  { name: "Magotlhwane", cadastreAreaId: "96", locationType: "Village" },
  { name: "Gasita", cadastreAreaId: "170", locationType: "Village" },
  { name: "Ntlhantlhe", cadastreAreaId: "95", locationType: "Village" },
  { name: "Kanye", cadastreAreaId: "143", locationType: "Village" },
  { name: "Selokolela", cadastreAreaId: "162", locationType: "Village" },
  { name: "Ranaka", cadastreAreaId: "136", locationType: "Village" },
  { name: "Polokwe", cadastreAreaId: "142", locationType: "Village" },
  { name: "Lekgolobotlo", cadastreAreaId: "94", locationType: "Village" },
  { name: "Maokane", cadastreAreaId: "173", locationType: "Village" },
  { name: "Lefhoko", cadastreAreaId: "176", locationType: "Village" },
  { name: "Sesung", cadastreAreaId: "167", locationType: "Village" },
  { name: "Moshaneng", cadastreAreaId: "163", locationType: "Village" },
  { name: "Bikwe", cadastreAreaId: "138", locationType: "Village" },
  { name: "Lotlhakane West", cadastreAreaId: "141", locationType: "Village" },
  { name: "Tsonyane", cadastreAreaId: "169", locationType: "Village" },
  { name: "Seherelela", cadastreAreaId: "168", locationType: "Village" },
  { name: "Manyana", cadastreAreaId: "137", locationType: "Village" },
  { name: "Tshwaane", cadastreAreaId: "164", locationType: "Village" },
  { name: "Betesankwe", cadastreAreaId: "177", locationType: "Village" },
  { name: "Goo-kodisa", cadastreAreaId: "139", locationType: "Village" },
  { name: "Moshupa", cadastreAreaId: "140", locationType: "Village" },
  { name: "Sese", cadastreAreaId: "178", locationType: "Village" },
  { name: "Itholoke", cadastreAreaId: "184", locationType: "Village" },
  { name: "Mokhomma", cadastreAreaId: "175", locationType: "Village" },
  { name: "Khakhea", cadastreAreaId: "186", locationType: "Village" },
  { name: "Kutuku", cadastreAreaId: "185", locationType: "Village" },
  { name: "Samane", cadastreAreaId: "174", locationType: "Village" },
  { name: "Ralekgetho", cadastreAreaId: "165", locationType: "Village" },
  { name: "Thankane", cadastreAreaId: "172", locationType: "Village" },
  { name: "Khonkhwa", cadastreAreaId: "182", locationType: "Village" },
  { name: "Keng", cadastreAreaId: "183", locationType: "Village" },
  { name: "Pitseng", cadastreAreaId: "166", locationType: "Village" },
  { name: "Mabutsane", cadastreAreaId: "187", locationType: "Village" },
  { name: "Mahotshwane", cadastreAreaId: "180", locationType: "Village" },
  { name: "Kokong", cadastreAreaId: "190", locationType: "Village" },
  { name: "Sekoma", cadastreAreaId: "181", locationType: "Village" },
  { name: "Kanaku", cadastreAreaId: "188", locationType: "Village" },
  { name: "Wildlife Management Area", cadastreAreaId: "189", locationType: "Village" },
  { name: "Morwamosu", cadastreAreaId: "191", locationType: "Village" },
  { name: "Mogonye", cadastreAreaId: "93", locationType: "Village" },
  { name: "Molete", cadastreAreaId: "152", locationType: "Village" },
  { name: "Phitshane Molopo", cadastreAreaId: "150", locationType: "Village" },
  { name: "Mabule", cadastreAreaId: "155", locationType: "Village" },
  { name: "Tshidilamolomo", cadastreAreaId: "154", locationType: "Village" },
  { name: "Mmakgori", cadastreAreaId: "153", locationType: "Village" },
  { name: "Leporung", cadastreAreaId: "151", locationType: "Village" },
  { name: "Maisane", cadastreAreaId: "134", locationType: "Village" },
  { name: "Lorwana", cadastreAreaId: "131", locationType: "Village" },
  { name: "Oodi", cadastreAreaId: "20", locationType: "Village" },
  { name: "Modipane", cadastreAreaId: "19", locationType: "Village" },
  { name: "Morwa", cadastreAreaId: "22", locationType: "Village" },
  { name: "Bokaa", cadastreAreaId: "24", locationType: "Village" },
  { name: "Malotwane", cadastreAreaId: "26", locationType: "Village" },
  { name: "Mochudi", cadastreAreaId: "28", locationType: "Village" },
  { name: "Rasesa", cadastreAreaId: "25", locationType: "Village" },
  { name: "Dikgonnye", cadastreAreaId: "27", locationType: "Village" },
  { name: "Ramotlabaki", cadastreAreaId: "32", locationType: "Village" },
  { name: "Leshibitse", cadastreAreaId: "33", locationType: "Village" },
  { name: "Artesia/mosomane", cadastreAreaId: "31", locationType: "Village" },
  { name: "Oliphant's Drift", cadastreAreaId: "30", locationType: "Village" },
  { name: "Kgomodiatshana", cadastreAreaId: "34", locationType: "Village" },
  { name: "Ramonaka", cadastreAreaId: "16", locationType: "Village" },
  { name: "Mmathubudukwane", cadastreAreaId: "17", locationType: "Village" },
  { name: "Malolwane", cadastreAreaId: "29", locationType: "Village" },
  { name: "Pilane", cadastreAreaId: "23", locationType: "Village" },
  { name: "Dikwididi", cadastreAreaId: "18", locationType: "Village" },
  { name: "Mabalane", cadastreAreaId: "15", locationType: "Village" },
  { name: "Matebele", cadastreAreaId: "21", locationType: "Village" },
  { name: "Sikwane", cadastreAreaId: "14", locationType: "Village" },
  { name: "Marojane", cadastreAreaId: "115", locationType: "Village" },
  { name: "Hebron", cadastreAreaId: "116", locationType: "Village" },
  { name: "Logagane", cadastreAreaId: "117", locationType: "Village" },
  { name: "Borobadilepe", cadastreAreaId: "118", locationType: "Village" },
  { name: "Tswagare", cadastreAreaId: "114", locationType: "Village" },
  { name: "Madingwane", cadastreAreaId: "119", locationType: "Village" },
  { name: "Ngwatsau", cadastreAreaId: "125", locationType: "Village" },
  { name: "Sheepfarm", cadastreAreaId: "124", locationType: "Village" },
  { name: "Rakhuna", cadastreAreaId: "106", locationType: "Village" },
  { name: "Pitsane Photlokwe", cadastreAreaId: "126", locationType: "Village" },
  { name: "Metlojane", cadastreAreaId: "120", locationType: "Village" },
  { name: "Goodhope", cadastreAreaId: "123", locationType: "Village" },
  { name: "Tlhareseleele", cadastreAreaId: "105", locationType: "Village" },
  { name: "Malokaganyane", cadastreAreaId: "127", locationType: "Village" },
  { name: "Mogwalale", cadastreAreaId: "122", locationType: "Village" },
  { name: "Bethel", cadastreAreaId: "102", locationType: "Village" },
  { name: "Kgoro", cadastreAreaId: "128", locationType: "Village" },
  { name: "Molete", cadastreAreaId: "112", locationType: "Village" },
  { name: "Ditlharapa", cadastreAreaId: "111", locationType: "Village" },
  { name: "Phihetswane", cadastreAreaId: "110", locationType: "Village" },
  { name: "Makokwe", cadastreAreaId: "109", locationType: "Village" },
  { name: "Papatlo", cadastreAreaId: "108", locationType: "Village" },
  { name: "Ramatlabama", cadastreAreaId: "107", locationType: "Village" },
  { name: "Mokatako", cadastreAreaId: "113", locationType: "Village" },
  { name: "Cwaanyaneng", cadastreAreaId: "121", locationType: "Village" },
  { name: "Pitsane", cadastreAreaId: "104", locationType: "Village" },
  { name: "Dinatshana", cadastreAreaId: "103", locationType: "Village" },
  { name: "Ramotswa", cadastreAreaId: "8", locationType: "Village" },
  { name: "Lobatse", cadastreAreaId: "12", locationType: "Town" },
  { name: "Notwane Farms", cadastreAreaId: "4", locationType: "Farms" },
  { name: "Mogobane", cadastreAreaId: "9", locationType: "Village" },
  { name: "Otse", cadastreAreaId: "10", locationType: "Village" },
  { name: "Lobatse Block of Farms", cadastreAreaId: "11", locationType: "Farms" },
  { name: "Gaborone", cadastreAreaId: "1", locationType: "Village" },
  { name: "Tlokweng", cadastreAreaId: "3", locationType: "Farms" },
  { name: "Gaborone Block of Farms", cadastreAreaId: "7", locationType: "Farms" },
  { name: "Lobatse Block of Farms", cadastreAreaId: "13", locationType: "Farms" },
  { name: "Ruretse Farms", cadastreAreaId: "2", locationType: "Farms" },
  { name: "Forest Hill Farms", cadastreAreaId: "5", locationType: "Farms" },
  { name: "Mmokolodi", cadastreAreaId: "6", locationType: "Village" },
  { name: "Bokspits", cadastreAreaId: "213", locationType: "Village" },
  { name: "Vaalhoek", cadastreAreaId: "212", locationType: "Village" },
  { name: "Rappels Pan", cadastreAreaId: "211", locationType: "Village" },
  { name: "Khuis", cadastreAreaId: "209", locationType: "Village" },
  { name: "Gakhibane", cadastreAreaId: "210", locationType: "Village" },
  { name: "Middelpits", cadastreAreaId: "208", locationType: "Village" },
  { name: "Kolonkwaneng", cadastreAreaId: "206", locationType: "Village" },
  { name: "Struizendam", cadastreAreaId: "214", locationType: "Village" },
  { name: "Khawa", cadastreAreaId: "215", locationType: "National Parks and Forest Reserves" },
  { name: "Kalahari Trans-Frontier Park", cadastreAreaId: "216", locationType: "Village" },
  { name: "Tshabong", cadastreAreaId: "205", locationType: "Village" },
  { name: "Maralaleng", cadastreAreaId: "201", locationType: "Village" },
  { name: "Maleshe", cadastreAreaId: "204", locationType: "Village" },
  { name: "Khisa/ Maralaleng", cadastreAreaId: "203", locationType: "Village" },
  { name: "Omaweneno", cadastreAreaId: "202", locationType: "Village" },
  { name: "Phepheng", cadastreAreaId: "199", locationType: "Village" },
  { name: "Werda", cadastreAreaId: "198", locationType: "Village" },
  { name: "Inalegolo", cadastreAreaId: "193", locationType: "Farms" },
  { name: "Molopo Farms", cadastreAreaId: "196", locationType: "Village" },
  { name: "Kokotsha", cadastreAreaId: "195", locationType: "Village" },
  { name: "Lokgwabe", cadastreAreaId: "224", locationType: "Village" },
  { name: "Phuduhudu", cadastreAreaId: "192", locationType: "Village" },
  { name: "Tshane", cadastreAreaId: "225", locationType: "Village" },
  { name: "Hukuntsi", cadastreAreaId: "223", locationType: "Village" },
  { name: "Zutshwa", cadastreAreaId: "218", locationType: "Village" },
  { name: "Lehututu", cadastreAreaId: "226", locationType: "Village" },
  { name: "Kang", cadastreAreaId: "228", locationType: "Village" },
  { name: "Monong", cadastreAreaId: "222", locationType: "Village" },
  { name: "Make", cadastreAreaId: "227", locationType: "Village" },
  { name: "Hunhukwe", cadastreAreaId: "221", locationType: "Village" },
  { name: "Ngwatle", cadastreAreaId: "219", locationType: "Village" },
  { name: "Ncaang", cadastreAreaId: "220", locationType: "Village" },
  { name: "Ukhwi", cadastreAreaId: "217", locationType: "Village" },
  { name: "Khisa", cadastreAreaId: "200", locationType: "Village" },
  { name: "Makopong", cadastreAreaId: "194", locationType: "Village" },
  { name: "Bray", cadastreAreaId: "197", locationType: "Village" },
  { name: "Bogogobo", cadastreAreaId: "207", locationType: "Farms" },
  { name: "Metsimansho", cadastreAreaId: "232", locationType: "Village" },
  { name: "Kacgae", cadastreAreaId: "229", locationType: "Village" },
  { name: "New Xangas", cadastreAreaId: "236", locationType: "Village" },
  { name: "Ncojane", cadastreAreaId: "231", locationType: "Farms" },
  { name: "Xangas Farms", cadastreAreaId: "238", locationType: "Village" },
  { name: "Karakubis", cadastreAreaId: "239", locationType: "Village" },
  { name: "Charleshill", cadastreAreaId: "237", locationType: "Village" },
  { name: "West Hanahai", cadastreAreaId: "243", locationType: "Town" },
  { name: "Ghanzi Township", cadastreAreaId: "247", locationType: "Village" },
  { name: "Dkar", cadastreAreaId: "248", locationType: "Village" },
  { name: "Kuke", cadastreAreaId: "251", locationType: "Farms" },
  { name: "Ghanzi Farms", cadastreAreaId: "246", locationType: "National Parks and Forest Reserves" },
  { name: "Central Kalahari Game Reserve", cadastreAreaId: "253", locationType: "Village" },
  { name: "New Xade", cadastreAreaId: "252", locationType: "Village" },
  { name: "Bere", cadastreAreaId: "230", locationType: "Village" },
  { name: "Qabo", cadastreAreaId: "250", locationType: "Village" },
  { name: "East Hanahai", cadastreAreaId: "244", locationType: "Village" },
  { name: "Makunda", cadastreAreaId: "235", locationType: "Village" },
  { name: "Kule", cadastreAreaId: "234", locationType: "Village" },
  { name: "Grootlaagte", cadastreAreaId: "249", locationType: "Village" },
  { name: "Okwa-Gwana", cadastreAreaId: "241", locationType: "Village" },
  { name: "Kalkfontein", cadastreAreaId: "240", locationType: "Village" },
  { name: "Ncojane", cadastreAreaId: "233", locationType: "Village" },
  { name: "Chobokwane", cadastreAreaId: "242", locationType: "Village" },
  { name: "Hanahai Farms", cadastreAreaId: "245", locationType: "Village" },
  { name: "Wma Ng/14", cadastreAreaId: "323", locationType: "Village" },
  { name: "Wma Ng/13", cadastreAreaId: "322", locationType: "Village" },
  { name: "Wma Ng/15", cadastreAreaId: "325", locationType: "Village" },
  { name: "Wma Ng/16", cadastreAreaId: "324", locationType: "Village" },
  { name: "Wma Ng/20", cadastreAreaId: "328", locationType: "Village" },
  { name: "Khwai", cadastreAreaId: "326", locationType: "Village" },
  { name: "Upper Selinda", cadastreAreaId: "318", locationType: "Village" },
  { name: "Jao", cadastreAreaId: "293", locationType: "Village" },
  { name: "Uppr Selinda", cadastreAreaId: "317", locationType: "National Parks and Forest Reserves" },
  { name: "Moremi Game Reserve", cadastreAreaId: "330", locationType: "Village" },
  { name: "Mababe", cadastreAreaId: "331", locationType: "Village" },
  { name: "Wma Ng/42", cadastreAreaId: "332", locationType: "Village" },
  { name: "Khwai", cadastreAreaId: "327", locationType: "Village" },
  { name: "Wma Ng/25", cadastreAreaId: "287", locationType: "Village" },
  { name: "Wma Ng/26", cadastreAreaId: "286", locationType: "Village" },
  { name: "Wma Ng/43", cadastreAreaId: "336", locationType: "Village" },
  { name: "Sankuyo WMA NG/34", cadastreAreaId: "279", locationType: "Village" },
  { name: "Sankuyo", cadastreAreaId: "280", locationType: "Village" },
  { name: "Mogogelo/Boro", cadastreAreaId: "283", locationType: "Village" },
  { name: "Nokaneng", cadastreAreaId: "270", locationType: "Village" },
  { name: "Qangwa", cadastreAreaId: "269", locationType: "Village" },
  { name: "Kauxwi", cadastreAreaId: "307", locationType: "Village" },
  { name: "Wma Ng/30", cadastreAreaId: "273", locationType: "Village" },
  { name: "Wma Ng/47", cadastreAreaId: "335", locationType: "National Parks and Forest Reserves" },
  { name: "Nxai National Park", cadastreAreaId: "334", locationType: "Village" },
  { name: "Wma Ng/29", cadastreAreaId: "272", locationType: "Village" },
  { name: "Wma Ng/45", cadastreAreaId: "337", locationType: "Village" },
  { name: "Phuduhudu", cadastreAreaId: "338", locationType: "Village" },
  { name: "Wma Ng/21", cadastreAreaId: "329", locationType: "Village" },
  { name: "Wma Ng/31", cadastreAreaId: "281", locationType: "Village" },
  { name: "Wma Ng/27a", cadastreAreaId: "285", locationType: "Village" },
  { name: "Mogogelo/Boro", cadastreAreaId: "282", locationType: "Village" },
  { name: "Wma Ng/27b", cadastreAreaId: "284", locationType: "Village" },
  { name: "Xaxa", cadastreAreaId: "268", locationType: "Village" },
  { name: "Toteng Ranches", cadastreAreaId: "256", locationType: "Village" },
  { name: "Tsau", cadastreAreaId: "267", locationType: "Village" },
  { name: "Xaixai", cadastreAreaId: "263", locationType: "Village" },
  { name: "Kareng", cadastreAreaId: "264", locationType: "Village" },
  { name: "Semboyo", cadastreAreaId: "266", locationType: "Village" },
  { name: "Makakung", cadastreAreaId: "265", locationType: "Village" },
  { name: "Sehitwa", cadastreAreaId: "260", locationType: "Village" },
  { name: "Matsaudi", cadastreAreaId: "277", locationType: "Village" },
  { name: "Shorobe", cadastreAreaId: "278", locationType: "Village" },
  { name: "Nxaraga", cadastreAreaId: "258", locationType: "Village" },
  { name: "Chanoga", cadastreAreaId: "275", locationType: "Village" },
  { name: "Makalamabedi", cadastreAreaId: "276", locationType: "Village" },
  { name: "Toteng", cadastreAreaId: "259", locationType: "Village" },
  { name: "Komana", cadastreAreaId: "257", locationType: "Village" },
  { name: "Maun", cadastreAreaId: "274", locationType: "Village" },
  { name: "Hainaveld Phase1 Ranches", cadastreAreaId: "254", locationType: "Village" },
  { name: "Somelo", cadastreAreaId: "255", locationType: "Village" },
  { name: "Bodibeng", cadastreAreaId: "262", locationType: "Village" },
  { name: "Bothathogo", cadastreAreaId: "261", locationType: "Village" },
  { name: "Ikoga", cadastreAreaId: "297", locationType: "Village" },
  { name: "Sepopa", cadastreAreaId: "299", locationType: "Village" },
  { name: "Tsodilo", cadastreAreaId: "298", locationType: "Village" },
  { name: "Kajaja", cadastreAreaId: "300", locationType: "Village" },
  { name: "Nxamasere", cadastreAreaId: "301", locationType: "Village" },
  { name: "Chukumuchu", cadastreAreaId: "296", locationType: "Village" },
  { name: "Samochina", cadastreAreaId: "303", locationType: "Village" },
  { name: "Gani", cadastreAreaId: "305", locationType: "Village" },
  { name: "Shakawe", cadastreAreaId: "304", locationType: "Village" },
  { name: "Mohembo", cadastreAreaId: "306", locationType: "Village" },
  { name: "Tubu", cadastreAreaId: "288", locationType: "Village" },
  { name: "Etsha 1", cadastreAreaId: "291", locationType: "Village" },
  { name: "Etsha 6", cadastreAreaId: "292", locationType: "Village" },
  { name: "Etsha 13", cadastreAreaId: "294", locationType: "Village" },
  { name: "Nxauxau", cadastreAreaId: "295", locationType: "Village" },
  { name: "Gumare", cadastreAreaId: "289", locationType: "Village" },
  { name: "Mokgacha", cadastreAreaId: "314", locationType: "Village" },
  { name: "Mogotlho", cadastreAreaId: "313", locationType: "Village" },
  { name: "Gudigwa", cadastreAreaId: "321", locationType: "Village" },
  { name: "Xakao", cadastreAreaId: "308", locationType: "Village" },
  { name: "Ngarange", cadastreAreaId: "309", locationType: "Village" },
  { name: "Sekondomboro", cadastreAreaId: "312", locationType: "Village" },
  { name: "Tovera", cadastreAreaId: "310", locationType: "Village" },
  { name: "Ng/11", cadastreAreaId: "311", locationType: "Village" },
  { name: "Eretsha", cadastreAreaId: "319", locationType: "Village" },
  { name: "Gunotsoga", cadastreAreaId: "316", locationType: "Village" },
  { name: "Beetsha", cadastreAreaId: "320", locationType: "Village" },
  { name: "Seronga", cadastreAreaId: "315", locationType: "Village" },
  { name: "Ng/3", cadastreAreaId: "290", locationType: "Village" },
  { name: "Makgadikgadi National Park", cadastreAreaId: "339", locationType: "Village" },
  { name: "Patayamatebele", cadastreAreaId: "534", locationType: "Village" },
  { name: "Matopi", cadastreAreaId: "535", locationType: "Village" },
  { name: "Ditladi", cadastreAreaId: "533", locationType: "Village" },
  { name: "Shashe Bridge", cadastreAreaId: "532", locationType: "Village" },
  { name: "Tatisiding", cadastreAreaId: "531", locationType: "Farms" },
  { name: "Tati Farms", cadastreAreaId: "530", locationType: "Village" },
  { name: "Matsiloje", cadastreAreaId: "537", locationType: "Farms" },
  { name: "Matshelagabedi Farm", cadastreAreaId: "540", locationType: "Village" },
  { name: "Matshelagabedi", cadastreAreaId: "539", locationType: "Village" },
  { name: "Jackalas 2", cadastreAreaId: "541", locationType: "Village" },
  { name: "Mabudzane", cadastreAreaId: "542", locationType: "Village" },
  { name: "Gulubane", cadastreAreaId: "527", locationType: "Village" },
  { name: "Tsamaya", cadastreAreaId: "544", locationType: "Village" },
  { name: "Siviya", cadastreAreaId: "543", locationType: "Village" },
  { name: "Masingwaneng", cadastreAreaId: "526", locationType: "Village" },
  { name: "Matenge", cadastreAreaId: "525", locationType: "Village" },
  { name: "Makaleng", cadastreAreaId: "524", locationType: "Village" },
  { name: "Themashanga", cadastreAreaId: "545", locationType: "Village" },
  { name: "Mambo", cadastreAreaId: "523", locationType: "Village" },
  { name: "Mowana", cadastreAreaId: "546", locationType: "Village" },
  { name: "Toteng", cadastreAreaId: "521", locationType: "Village" },
  { name: "Sechele", cadastreAreaId: "522", locationType: "Village" },
  { name: "Senyawe", cadastreAreaId: "547", locationType: "Village" },
  { name: "Tshesebe Block of Farms", cadastreAreaId: "549", locationType: "Village" },
  { name: "Tshe sebe", cadastreAreaId: "550", locationType: "Village" },
  { name: "Botalaote", cadastreAreaId: "520", locationType: "Village" },
  { name: "Letsholathebe", cadastreAreaId: "559", locationType: "Village" },
  { name: "Butale", cadastreAreaId: "548", locationType: "Farms" },
  { name: "North East Farms", cadastreAreaId: "528", locationType: "Village" },
  { name: "Pole", cadastreAreaId: "556", locationType: "Village" },
  { name: "Masunga", cadastreAreaId: "560", locationType: "Village" },
  { name: "Vukwi", cadastreAreaId: "518", locationType: "Village" },
  { name: "Kalakamati", cadastreAreaId: "519", locationType: "Village" },
  { name: "Mosojane", cadastreAreaId: "558", locationType: "Village" },
  { name: "Kgari", cadastreAreaId: "555", locationType: "Village" },
  { name: "Masukwane", cadastreAreaId: "557", locationType: "Village" },
  { name: "Mulambakwena", cadastreAreaId: "561", locationType: "Village" },
  { name: "Ramokgwebana", cadastreAreaId: "551", locationType: "Village" },
  { name: "Gambule", cadastreAreaId: "517", locationType: "Village" },
  { name: "Jackalas 1", cadastreAreaId: "552", locationType: "Village" },
  { name: "Sekakangwe", cadastreAreaId: "514", locationType: "Village" },
  { name: "Moroka", cadastreAreaId: "553", locationType: "Village" },
  { name: "Mapoka", cadastreAreaId: "554", locationType: "Village" },
  { name: "Nlapkhwane", cadastreAreaId: "562", locationType: "Village" },
  { name: "Gungwe", cadastreAreaId: "516", locationType: "Village" },
  { name: "Mbalambi", cadastreAreaId: "515", locationType: "Village" },
  { name: "Zwenshambe", cadastreAreaId: "563", locationType: "Village" },
  { name: "Mopane Gold Mine", cadastreAreaId: "536", locationType: "Village" },
  { name: "Tati Nickel Mine", cadastreAreaId: "538", locationType: "National Parks and Forest Reserves" },
  { name: "Francistown", cadastreAreaId: "529", locationType: "National Parks and Forest Reserves" },
  { name: "Sibuyu Forest Reserve", cadastreAreaId: "564", locationType: "Village" },
  { name: "Maikaelelo Forest Reserve", cadastreAreaId: "567", locationType: "National Parks and Forest Reserves" },
  { name: "Pandamatenga", cadastreAreaId: "569", locationType: "Village" },
  { name: "Kazuma Forest Reserve", cadastreAreaId: "570", locationType: "Village" },
  { name: "Kachikau", cadastreAreaId: "581", locationType: "Village" },
  { name: "Parakarungu", cadastreAreaId: "583", locationType: "National Parks and Forest Reserves" },
  { name: "Satau", cadastreAreaId: "582", locationType: "National Parks and Forest Reserves" },
  { name: "Kasane Forest Reserve Extension", cadastreAreaId: "572", locationType: "Village" },
  { name: "Chobe Forest Reserve", cadastreAreaId: "578", locationType: "National Parks and Forest Reserves" },
  { name: "Lesoma", cadastreAreaId: "573", locationType: "National Parks and Forest Reserves" },
  { name: "Chobe National Park", cadastreAreaId: "577", locationType: "National Parks and Forest Reserves" },
  { name: "Kasane Forest Reserve", cadastreAreaId: "574", locationType: "National Parks and Forest Reserves" },
]

// Quick lookup: village name → { cadastreAreaId, locationType }
export const VILLAGE_LOOKUP = VILLAGES.reduce((acc, v) => {
  acc[v.name] = v
  acc[v.name.toLowerCase()] = v
  return acc
}, {})

// Land Authorities (Administrative Districts) — per client correction: field
// is "Land Authority", not "Land Board".
export const LAND_AUTHORITIES = [
  "Central Administrative District",
  "Gaborone Administrative District",
  "Selebi Phikwe Administrative District",
  "Lobatse Administrative District",
  "Jwaneng Administrative District",
  "Francistown Administrative District",
  "Ghanzi Administrative District",
  "Chobe Administrative District",
]
